### PR TITLE
Several pickle files

### PR DESCRIPTION
**Pull request by erap129**
I really hope I got it right this time ;)

### CODE REVIEW

**Comment by shaypal5** [comment]
Tests are running here:
https://github.com/shaypal5/cachier/actions/runs/1157433842

Let's see how it goes.

**Comment by erap129** [comment]
Yeah, the truth is I'm kind of stumped on that delete_cache_file test and I see it fails in Github Actions as well. Will try and check it out later...

**Comment by erap129** [comment]
`test_delete_cache_file` fails for me even in the master branch. Any idea what's going on here?

**Comment by shaypal5** [comment]
What do you mean it fails for you even in the `master` branch? When you run tests when `master` is checked out for you locally? Because the latest commit on master builds successfully:

https://github.com/shaypal5/cachier/actions/runs/1034376261

**Pull request merged**
