### PR TITLE
refactor: clarify the casher arguments

### PR DESCRIPTION
**Pull request by Borda**
Adding prefixes similar to scikit-learn pipelines does clarify which arguments are for the function and which are for the wrapper... :flamingo: 
Moreover we can adapt the updating default so almost all arguments can be overwritten with a particular function call :magic_wand:

### CODE REVIEW

**Comment by shaypal5** [comment]
This is a major API breaking change, which will require the release of a new major version. It's sensible, but it means any new improvement coming after it won't be enjoyed by anyone not going back and changing their code.

Let's finish first with everything else you have up your sleeve, and then consider it again.

**Comment by Borda** [comment]
> This is a major API breaking change, which will require the release of a new major version.

yes, so I can preserve the actual with raising a deprecation warning and enabling the new naming, what do you think?

**Comment by shaypal5** [comment]
Yes, keeping both with a deprecation warning is a good idea for now.

**Comment by Borda** [comment]
> Yes, keeping both with a deprecation warning is a good idea for now.

cool, added related tests that these "old" args still work and deprecation is raised

**Review by shaypal5 — APPROVED** [review]

**Comment by shaypal5** [comment]
@Borda Same here.
Conflicts must be resolved.

**Comment by Borda** [comment]
> Conflicts must be resolved.

done :)

**Pull request merged**
