### PR TITLE
ci: drop environment config

### LINKED ISSUE #146: reduce number of events on a PR
@shaypal5 would it be possible to reduce the number of events in the PR? It is super long, and GH hides all intermediate comments, so the PR is much harder to follow... :confused: 
image

### PR DESCRIPTION
**Pull request by Borda**
Resolves #146 not sure if this `environment` option is really needed...

### CODE REVIEW

**Comment by shaypal5** [comment]
We do need it, though, to get the secrets that connect to MongoDB. @Borda 

image


Even if we transition to testing against a local MongoDB instance, I want us to know how to work with repo-level environments which grant access to repo secrets.

Maybe just the level of nesting? Let's find other such YAMLs using the environment key.

See the reference use in [Github documentation](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment):
```yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps
```

VS our use:
```yaml
name: Test

on:
  push:
  pull_request:
  schedule:
     # * is a special character in YAML so you have to quote this string
     # min hours day(month) month day(week)
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment:
      name: test
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        backend: ['local', 'db']
``

**Review by shaypal5 — CHANGES_REQUESTED** [review]
We need to find a way to use environments without this happening.

Also, as long as we're testing against the live, Atlas-hosted, MongoDB instance, we can't drop this without blocking mongodb-bound tests' access to it, as the rely on this environment to read repo-level secrets for authentication against it.

**Comment by Borda** [comment]
> We need to find a way to use environments without this happening.

as the secret for `checkdocs` and `test` are the same you can set them as repository secrets so the env is not needed, but fine to leave it for now :)

**Comment by shaypal5** [comment]
Yes, we can kill the checkdocs env completely.

Please alter just the checkdocs yaml for now and lets see how this goes.

We need to find, in some later date, how big projects that do use secrets manage this without PR conversation clutter.

**Pull request closed without merging**
