### PR TITLE
Handle function defaults correctly

### PR DESCRIPTION
**Pull request by filyp**

### CODE REVIEW

**Comment by fsondej** [comment]
Tests on travis fail, but it looks that not because of my added test case
https://travis-ci.org/github/shaypal5/cachier/jobs/766383557
I had this same error when trying to run them locally wthout any changes

**Comment by shaypal5** [comment]
Ok. I see now that environment variables are NEVER going to be available for PRs on Travis, so I'll have to pull this to a branch here to test.

**Review by shaypal5 — APPROVED** [review]
Looks good.

**Comment by shaypal5** [comment]
Tests are running here:
https://travis-ci.org/github/shaypal5/cachier/builds/769118950

@fsondej please let me know if this help with your work on the numpy issue thingy.
If this is good for now, I can rebase this branch to master.
If you have a code change (that is not test related) open a separate PR for it, and I'll pull to a branch here so we can see Mongo-core tests for it. And let me know if other tests are not working locally - this is something that I need to nail down in the contributor guidelines.

**Comment by fsondej** [comment]
Sorry, I'm not using cachier for now, and I won't have time to do this PR :(
If someone needs this in the future, the needed code is in https://github.com/shaypal5/cachier/issues/42

**Pull request merged**
