### PR TITLE
Include cachier.scripts in packages

### PR DESCRIPTION
**Pull request by thewchan**
Include `cachier.scripts` explicitly in packages.

### CODE REVIEW

**Comment by shaypal5** [comment]
Why is this required? Is the CLI not installed without this addition?

**Comment by thewchan** [comment]
Seems that way on my end? Or perhaps use `find_packages()` in Setuptools?

**Comment by shaypal5** [comment]
Ok, let's just merge it then.

**Review by lordjabez — APPROVED** [review]

**Comment by shaypal5** [comment]
Released in `v2.0.2`

**Pull request merged**
