### PR TITLE
convert `args` to `kwargs` to reduce nb of unique keys

### LINKED ISSUE #138: convert `args` to `kwargs` -> reduce keys for identical inputs
It seems that calling the same sample function with identical argument values can yield two different entry keys; see an example of a simple function:
```py
def sample_keys(a, b, c=3):
    return a + b + c
```
The default hash function 
https://github.com/python-cachier/cachier/blob/28c8d0d6beece98e64eb4af7a013fe6562c87776/cachier/core.py#L83-L89
will give these keys:
- for `sample_keys(1, 2, c=3)` gives:
	```py
	args, kwds = (1, 2), {"c": 3}
	functools._make_key(args, kwds, typed=True)
	Out[1]: [1, 2, <object at 0x7fc500943380>, 'c', 3, int, int, int]
	```
- for `sample_keys(1, b=2, c=3)` gives:
	```py
	args, kwds = (1,), {"b": 2, "c": 3}
	functools._make_key(args, kwds, typed=True)
	Out[2]: [1, <object at 0x7fc500943380>, 'b', 2, 'c', 3, int, int, int]
	```

### PR DESCRIPTION
**Pull request by Borda**
resolves #138, see details in the issue

cc: @shaypal5

### CODE REVIEW

**Comment by shaypal5** [comment]
Hey @Borda,

Please note that your code fails some non-mongo-core-related tests.
Once you only fail mongo-core-related tests, I can pull this into a dev branch to run against a live MongoDB instance, to make sure such failures are not due to running against an in-memory mock of MongoDB.

**Comment by Borda** [comment]
> Please note that your code fails some non-mongo-core-related tests.

yes, looking into it... in addition I may have two suggestion
- run mongo server as part of the job so also all forked PRs will be tested
I see you have also pytest markers, so hoa about split the testing into two steps `pytest tests/ -m "not mongo"` and `pytest tests/ -m "mongo"` so it is easier to spot the issue (fine to send it in separate PR :rabbit:)

**Comment by shaypal5** [comment]
> > Please note that your code fails some non-mongo-core-related tests.
> 
> yes, looking into it... in addition, I may have two suggestions
> 
> * run mongo server as part of the job so that all forked PRs will be tested
> * I see you also have `pytest` markers, so how about splitting the testing into two steps `pytest tests/ -m "not mongo"` and `pytest tests/ -m "mongo"` so it is easier to spot the issue (fine to send it in separate PR [ci: split tests for local / db #142](https://github.com/python-cachier/cachier/pull/142) 🐰)

1. Nice. Waiting for updates on resolution of these bugs.
2. Sounds good. A nice future to-do.
3. Sounds good! :)

**Comment by Borda** [comment]
@shaypal5 seems to be passing now... :chipmunk:

**Comment by shaypal5** [comment]
Great! Let's finish with the test cleanup PRs first, then you can rebase over them and we can get cleaner tests results; we'll move directly to vs-real-mongo testing after that.

**Pull request merged**
