### PR TITLE
typing: adding check and fixing

### PR DESCRIPTION
**Pull request by Borda**
reaction to https://github.com/python-cachier/cachier/issues/246#issuecomment-2433352234
so there are still a few typing issues to be fixed 🐰 

will finish the test fixing after #248 and #249

### CODE REVIEW

**Comment by Borda** [comment]
remaining:
```
FAILED tests/test_general.py::test_runtime_handling[pickle] - assert 3 == -1
 +  where 3 = <function test_runtime_handling.<locals>.fn_minus at 0x106041510>(1, 2)
 +    where <function test_runtime_handling.<locals>.fn_minus at 0x106041510> = <function cachier.<locals>._cachier_decorator at 0x106041240>(<function test_runtime_handling.<locals>.fn_minus at 0x106040a60>)
FAILED tests/test_general.py::test_partial_handling - assert 3 == -1
 +  where 3 = <function cachier.<locals>._cachier_decorator.<locals>.func_wrapper at 0x106042440>()
 +    where <function cachier.<locals>._cachier_decorator.<locals>.func_wrapper at 0x106042440> = <function cachier.<locals>._cachier_decorator at 0x1060423b0>(functools.partial(<function test_partial_handling.<locals>.fn_minus at 0x106042290>, 1))
```

**Comment by shaypal5** [comment]
Nice. The other two PRs are merged.
Should I release a version now, or wait for this PR?
@Borda

**Comment by Borda** [comment]
> Nice. The other two PRs are merged. Should I release a version now, or wait for this PR? 

up to you but it shall be resolved now :)

**Review by shaypal5 — APPROVED** [review]
Awesome work, as usual. :)

**Pull request merged**
