### PR TITLE
Change wait_on_entry_calc to use while loop instead of recursion

### PR DESCRIPTION
**Pull request by ofirnk**
From https://github.com/shaypal5/cachier/pull/25/ , just rebased

### CODE REVIEW

**Comment by ofirnk** [comment]
@shaypal5 can you approve running workflow on this PR?

For reference, I've created [this PR](https://github.com/ofirnk/cachier/pull/1) which passes all tests.

I've narrowed the scope a bit and disabled few tests so that it works to success:
https://github.com/ofirnk/cachier/pull/1

**Comment by shaypal5** [comment]
Sure, just approved.

**Comment by ofirnk** [comment]
CI failed due to other reasons
https://github.com/shaypal5/cachier/runs/3131965370

Tried narrowing down scope to temporarily test only specific test file, so will need approval again..

**Comment by ofirnk** [comment]
Just verified via monkey-patching:

```py
from cachier.pickle_core import _PickleCore

PC = _PickleCore
def patched_wait_on_entry_calc(self, key):
    with self.lock:
        self._reload_cache()
        entry = self._get_cache()[key]
        if not entry["being_calculated"]:
            return entry["value"]
    event_handler = _PickleCore.CacheChangeHandler(filename=self._cache_fname(), core=self, key=key)
    from watchdog.observers import Observer
    observer = Observer()
    event_handler.inject_observer(observer)
    observer.schedule(event_handler, path=self.expended_cache_dir, recursive=True)
    observer.start()
    while observer.is_alive():
        observer.join(timeout=1.0)
    return event_handler.value

PC.wait_on_entry_calc = patched_wait_on_entry_calc

```

Previously after ~20 minutes we started to face the mentioned error, now it worked >1 hour

**Comment by shaypal5** [comment]
Arrrgggghhh! That's annoying!
It seems like the job is not reading the secrets used to set up env vars with auth details for the MongoDB test server.
Let me look into it... :)

**Comment by shaypal5** [comment]
Ok, after quite some time looking into this, I can confidently say there's no real solution for this.
PRs ain't gonna run with secrets. Not gonna happen, techinically.

So from now on I'm going to pull PRs into branches and we'll work from there (as branches of this repo all have access to secrets).
I'm going to go ahead and do this, and we'll see what's what.

**Comment by shaypal5** [comment]
This should be the run:
https://github.com/shaypal5/cachier/actions/runs/1116177874

@ofirnk

**Comment by ofirnk** [comment]
> Ok, after quite some time looking into this, I can confidently say there's no real solution for this.
> PRs ain't gonna run with secrets. Not gonna happen, techinically.
> 
> So from now on I'm going to pull PRs into branches and we'll work from there (as branches of this repo all have access to secrets).
> I'm going to go ahead and do this, and we'll see what's what.

Right, I also didn't find a better option ..

CI fails now, and I'm not sure why. It passes on windows-latest for 3.6, 3.8 and 3.9 - fails only 3.7 .

Perhaps some race condition?
It would be hard (=impossible) for me to debug it due to a complete windows env setup that I don't have, unfortunately

**Pull request merged**
