### PR TITLE
ci: replace dead safety test with GH actions

### PR DESCRIPTION
**Pull request by Borda**

### CODE REVIEW

**Comment by Borda** [comment]
well, maybe drop it completely?

**Comment by shaypal5** [comment]
Wait, leave this open.

I'm trying to solve this by dumping `setup.py`'s `install_requires` contents into a temp requirements.txt file. `safety check` should then work.

**Comment by Borda** [comment]
> I'm trying to solve this by dumping `setup.py`'s `install_requires` contents into a temp requirements.txt file. `safety check` should then work.

ok, that would work too, so you are working on it or shall I append it here?

**Comment by shaypal5** [comment]
It's done, and works locally. You're welcome to take it from here if the workflow needs fixes. I'm out for the day. @Borda

**Comment by Borda** [comment]
the name in action is strange https://github.com/aufdenpunkt/python-safety-check/issues/2#issuecomment-1944753504

**Comment by shaypal5** [comment]
We don't want to rely on that action. A PR to fix that typo has been sitting there since March 2023 (!):
https://github.com/aufdenpunkt/python-safety-check/pull/8

I forked and fixed the action, republishing it under a similar name:
https://github.com/marketplace/actions/python-safety-checker

@Borda

**Review by shaypal5 — APPROVED** [review]

**Pull request merged**
