### PR TITLE
Hash every args including pandas and numpy objects.

### PR DESCRIPTION
**Pull request by fx-kirin**
I just would like to show you an example of the hash implementation.

https://github.com/shaypal5/cachier/pull/9#issuecomment-571868760

### CODE REVIEW

**Comment by shaypal5** [comment]
This looks really nice, @fx-kirin !
Once you solve the Python 2.7 test problem (seems like a numpy-pandas version mismatch issue), and as long as you test it thoroughly - I've read the existing two tests, but do try to come up with more - we can merge this! :)

Of course, given that code coverage and quality do not go down. :)

**Comment by fx-kirin** [comment]
I'm not sure how to fix that dependency problem because I didn't specify any version of them. I think that's the problem of pandas and numpy themselves. The modification of code looks quite ok to me. How do you think?

**Comment by shaypal5** [comment]
You know what? Screw it. I'm dropping support for Python 2.7. It ended it life cycle and the community should move away from it anyway.

**Comment by shaypal5** [comment]
Merged! I think it will pass all the tests and is A-OK test coverage and code quality wise!

Thank you for the contribution!

**Comment by shaypal5** [comment]
Hey @fx-kirin ,

Unfortunately I had to roll back all hash-related additions due to issues #18 and #19 .
Any future attempt to implement this kind of feature should explicitly treat those issues, including testing for them using the code supplied by the reporter of the issues.

The `hash` branch contains all the changes before the revert commit. 

Bummer. :/
But maybe this can be solved! :)

**Pull request merged**
