### PR TITLE
Add global defaults including enable/disable

### LINKED ISSUE #56: Allow to globally specify the location of the cache dir
In addition to configuring the cache file path for each wrapped function, a way to globally change the location of the general cache directory for all `cachier` caches is required.

A possible API:

```python
>>> import cachier
>>> cachier.get_global_cache_dpath()
'/home/myuser/.cachier'
>>> cachier.set_global_cache_dpath('/home/opt/caches/')
>>> cachier.get_global_cache_dpath()
'/home/opt/caches/'
```

### LINKED ISSUE #100: disable caching or enable caching based on global arg
as an example, Id like to run cachier locally when processing some data but I do not want to have it enabled when running in the cloud.

### LINKED ISSUE #117: Can I set global settings?
Can I set the `cache_dir` globally instead of having to set it on every instance of the `@cachier` decorator?

### PR DESCRIPTION
**Pull request by lordjabez**
Adds new `set_default_params` function to allow setting of global defaults. See description in README and function header for details.

Also adds `enable_caching` and `disable_caching` functions so caching can be turned on or off across all decorators at any time.

Fixes #56 
Fixes #100 
Fixes #117

### CODE REVIEW

**Comment by lordjabez** [comment]
Still need to write up docs in the README, but almost there.

Also going to add global enable/disable caching functions since that's why I started down this road in the first place.

**Review by shaypal5 — APPROVED** [review]
I read through this! Looks great, and very extensively tested! Nice one, Judson! :)

**Comment by lordjabez** [comment]
@shaypal5 do you have an idea when you'll get a new release out with this PR? I've got some "day job" work blocked on being able to pull it into a CI/CD pipeline from PyPI. And yes I realize there are workarounds to that, but I'd rather just get it the official way.

**Comment by shaypal5** [comment]
Released as `v2.1.1`

**Pull request merged**
