### PR TITLE
Query decorated function if result is from cache

### LINKED ISSUE #46: Notify successful fresh cache retrieval
Hi, I'd like to propose an enhancement similar to `verbose_cache`. 

I will call the new keyword argument `notify_fresh`. The wrapped function will return a tuple where the second value indicates if the value was fresh from cache.

This will enable logic outside the scope of the cached function to make decisions based on whether the data came from the cache.

For example, let's pretend we have a snobby server that hates being asked too many questions in rapid succession. If we get our answer fresh from the cache, then we can ask the next question right away:

```` python
@cachier()
def small_talk_to_snobby_server(query):
    response = "I'm fine, thank you!"
    return response

if __name__ == "__main__":
    response, is_fresh = small_talk_to_snobby_server(query="How are you?", notify_fresh=True)
    if not is_fresh:
        sleep(60)
    response = small_talk_to_snobby_server(query="What are you up to these days?")
````

### Some self-critique
I find it rather clunky and API-breaking to make functions return a different data type than expected. I do not know any other way around this.

### PR DESCRIPTION
**Pull request by kitmonisit**
Decorated function gains a new attribute function, `is_from_cache`, which returns `True` if the result comes from the cache; otherwise `False`.

For example, if the decorated function is named `foo()`:

    >>> foo()
    >>> foo.is_from_cache()
    False
    >>> foo()
    >>> foo.is_from_cache()
    True

- Fixes #46
- Fixes #47

### CODE REVIEW

**Comment by kitmonisit** [comment]
@shaypal5 I know this is not what you suggested in https://github.com/shaypal5/cachier/issues/46#issuecomment-794168396, but hear me out for a bit:

I realized there was a need to encapsulate the `is_from_cache()` information, i.e. localized to the decorated function. In the existing code, there are provisions for manipulating the cache specific to the decorated function, such as `clear_cache()`. My implementation here follows that paradigm.

**Comment by shaypal5** [comment]
API-wise, you're right ― there are existing precedents to modifying, and actually enhancing, the decorated function's API with additional attributes, such as `clear_cache()`.

However, the use case here is different. `clear_cache()` clears an attribute that is unique to the function ― its cache ― and it thus make sense that the function is bound to the decorated function. In your case, the action is bound to a specific call of the function, and thus this is inherently not appropriate to bound it to the function, but rather to the call.

The practical implication is that this API is indeed not thread-safe: You might call `is_from_cache()` straight after the call to `foo()`, and still get an irrelevant result  if another call to `foo()` was made in another thread between the two calls. Since at the moment a significant feature of `cachier` ― and one which some work went into ― is that it is thread-safe, I would prefer not to break it for the current implementation suggestion.

I still think a simple listener object is the way to go, since it is bound to the call rather than the function. This is like future objects in various programming languages, that are implemented as per-call instances you get and query. So yeah, maybe something like this:

```python
call_info = cachier.Info()
foo(cachier_info=call_info)
if call_info.is_from cache:
    # do something
```

The more general name and structure of a call information object is intentional, since this is an easily expandable API, onto which we can graft additional functionalities for call-specific information (an obvious and useful example: get the time in which the value in the cache was produced).

Let me know what you think!
Shy

**Review by shaypal5 — CHANGES_REQUESTED** [review]
See my comment about the fundamental problems in this implementation - first among them is breaking thread-safety.

**Comment by kitmonisit** [comment]
Ah, wonderful. And here I thought I was being thread-safe by localizing the query but as you point out, it's exactly the opposite.  Let me take another swing at it!

**Comment by kitmonisit** [comment]
Regarding thread-safety, here is how I imagine a demonstration:

    from random import random
    from cachier import cachier, Info
    from concurrent.futures import ThreadPoolExecutor

    @cachier()
    def foo(arg):
        return random() 

    # This is thread-safe
    # Info object is unique to every call of caller (and subsequently, foo)

    def caller(arg):
        call_info = Info()
        return foo(arg, cachier_info=call_info)

    with ThreadPoolExecutor() as pool:
        arglist = [1, 1, 2, 3]
        results = list(pool.map(caller, arglist))


    # This is NOT thread-safe
    # Info object is shared among all concurrent calls of caller

    call_info = Info()

    def caller(arg):
        return foo(arg, cachier_info=call_info)

    with ThreadPoolExecutor() as pool:
        arglist = [1, 1, 2, 3]
        results = list(pool.map(caller, arglist))

Is that how you envisioned it, @shaypal5?

**Comment by shaypal5** [comment]
Just writing to say I didn't forget this. This is on my TO-DO list for very soon. :)

**Comment by shaypal5** [comment]
Yes, that looks good! 

I'm sorry for the extremely belated response!
You want to change the PR accordingly, so we can iron out the details?

**Comment by shaypal5** [comment]
Closed after being stale for a long time.
Please open a new PR if you with to contribute this feature at some point in the future.

**Pull request closed without merging**
