### PR TITLE
several pickle files

### PR DESCRIPTION
**Pull request by shaypal5**

### CODE REVIEW

**Comment by erap129** [comment]
hmm for some reason this contribution appears under the github account @eladrap, even though I made the PR via this account (erap129). Did you somehow add @eladrap manually? If so I would be glad if you can swap it so this work will appear under this account (erap129). Thanks.

**Comment by erap129** [comment]
Hi, are we missing anything for this to continue? Thanks :)

**Comment by erap129** [comment]
Really hate to nag but do you think we will follow through with this? Thanks.

**Comment by shaypal5** [comment]
Hey, all good. Good of you to nag.

**Comment by shaypal5** [comment]
I didn't change anything manually. I wouldn't even know how to try something like altering the username this appears under. Let me check if I can fix this, however.

**Comment by erap129** [comment]
Yeah it was me of course, I made a mess by confusing my private and work accounts. I amended the commit to change the author and made the PR again. It's my first open-source contribution so I guess I'm just checking off beginner mistakes :)

**Comment by shaypal5** [comment]
:)

**Pull request closed without merging**
