### PR TITLE
skip cashing for exceptions

### LINKED ISSUE #215: Cachier caches a None return value when a function raises an Exception
I notice this caches "None" when the function raises an Exception. Eg:
```py
@cachier.cachier(backend='memory',allow_none=True)
def tmp_test(a):
    raise Exception()

tmp_test(123)  # Raises Exception
tmp_test(123)  # Returns None
```

Is this WAI?

_Originally posted by @tashmore in https://github.com/python-cachier/cachier/issues/121#issuecomment-2098803095_

### PR DESCRIPTION
**Pull request by Borda**
resolves #215

some small cleaning and adding `completed` flag to the entry

### CODE REVIEW

**Comment by Borda** [comment]
well, confused about what "being_calculated" stands for...

**Comment by shaypal5** [comment]
> @shaypal5, confused about what "being_calculated" stands for...

For non-local cores, like MongoDB, and long calculations, and to allow cross-machine (basically cross-kernel) caching, this supports the case where the same code calls the same decorated function with the same arguments (lets say `a=3, b=5`) on two different kernels/machine, 1 second apart (for example), for a calculation that lasts 10 minutes.

The first calls create a new entry for the cache key derived for `a=3, b=5`, with `being_calculated == True` in the entry, then waits for the function to return (when it will return, it will cache the result in the existing entry and update `being_calculated == False`). After 1 second, the same decorated function will get called with the same arguments on some other machine; it will search the MongoDB and find out an entry already exists for this argument set, and will see `being_calculated == True`, and will thus wait for the existing calculation (function call) to finish without triggering a second (redundant) call to the wrapped function.

Kapich?

**Comment by Borda** [comment]
@shaypal5 made two dataclass refactoring #237 #239 to make my path to better understand the codebase

**Comment by Borda** [comment]
@shaypal5 seems to be fixed now if you could check it

**Review by shaypal5 — APPROVED** [review]
Great work, again!

**Pull request merged**
