### PR TITLE
Several pickle files

### PR DESCRIPTION
**Pull request by erap129**
I'm pretty sure I fixed the test that wasn't passing, it was a bug in the test of course. If you can run the tests again I would be very glad (like the previous time when I PR the tests don't seem to run properly).

### CODE REVIEW

**Comment by shaypal5** [comment]
There you go. The tests are running here:
https://github.com/shaypal5/cachier/actions/runs/1238426918

**Comment by erap129** [comment]
I saw that you updated the tests which fail in certain builds in my branch - maybe it will help this branch as well? (Allow test_bad_cache_file to fail). How should we proceed from here?

**Comment by shaypal5** [comment]
Yeah, I'll merge you when the only tests you fail is `test_bad_cache_file`, because it's a statistical tests in a sense anyway, but  your code currently also fails on `test_delete_cache_file`, which `master` does not.

Fix this and we can continue. Also, add documentation of this feature to `README.rst`, please. :)

Nearly there!

**Comment by erap129** [comment]
Are you sure? I'm pretty sure the previous `master` build failed also on `test_delete_cache_file` : https://github.com/shaypal5/cachier/runs/3612544249. Maybe I should merge your latest update to my branch and we'll try running the tests again? They all pass locally so it's kinda hard for me to think of any action items besides that.

**Comment by shaypal5** [comment]
And at least the latest `master` commit didn't fail on `test_delete_cache_file`:
https://github.com/shaypal5/cachier/actions/runs/1238487187

**Pull request merged**
